version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./db.env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres-data:
