# Generated by Django 5.0.3 on 2024-03-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
