# Generated by Django 5.0.3 on 2024-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SongRequests", "0003_song_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="song",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
