# Generated by Django 5.0.3 on 2024-03-13 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("MeetApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
