name: Django API test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cat requirements.txt
        pip install -r requirements.txt
    - name: Set environment variables
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "SQL_DATABASE=test_db" >> $GITHUB_ENV
        echo "SQL_USER=postgres" >> $GITHUB_ENV
        echo "SQL_PASSWORD=postgres" >> $GITHUB_ENV
        echo "SQL_HOST=localhost" >> $GITHUB_ENV
        echo "SQL_PORT=5432" >> $GITHUB_ENV
    - name: Wait for PostgreSQL to be ready
      run: |
        until PGPASSWORD=$SQL_PASSWORD psql -h "$SQL_HOST" -U "$SQL_USER" -d "$SQL_DATABASE" -c '\q'; do
          >&2 echo "Postgres is still unavailable - sleeping"
          sleep 1
        done
        >&2 echo "Postgres is up - executing command"
    - name: Run Database Migrations
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test
