name: 'Lint Code'
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Print working directory
      run: pwd
    - name: Run Linter
      run: |
        pwd
        find . -name "*.py" -exec flake8 --max-line-length=120 --ignore=W293,E111,E302,W292,E266 {} +
        echo "Linted all the python files successfully"